name: exblurf
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.6
  - plyfile=0.8.1
  - python=3.7.13
  - pip=22.3.1
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tqdm
  - configargparse
  - pip:
    - open3d
    - opencv-python-headless
    - tensorboardX>=2.0
    - matplotlib
    - scipy
    - scikit-learn
    - scikit-image
    - timm==0.6.7
    - imageio
    - imageio[ffmpeg]
    - pytorch3d
    - ./svox2
